### ISSUE TITLE
Naming of the repo

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-streams-operators#1]
Shouldn't it be "smallrye-reactive-streams-operators" to follow the spec name?

**Comment by kenfinnigan** [comment]
Didn't realize that was the full spec name, will adjust

**Comment by kenfinnigan** [comment]
Done

**Comment by cescoffier** [comment]
Man! You're fast!

**Comment by kenfinnigan** [comment]
I just happened to be sitting here checking things before going out for breakfast ;-)
