### ISSUE TITLE
Configure CI to run against Java 8, and 11

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-streams-operators#15]
We need to configure the CI to enforce the implementation works on different Java version.
Typically Java 8 and Java 11 need to be checked.

**Comment by cescoffier** [comment]
As Java 11 is not yet supported by Semaphore - postponed the issue, a manual check will be done.

@kenfinnigan maybe you know a workaround?

**Comment by kenfinnigan** [comment]
Looks it they currently only support up to JDK 10.

One option would be a custom DockerFile to use JDK 11 and have the build use that instead.

Couldn't find any details about when they might support JDK 11

**Comment by cescoffier** [comment]
Semaphore added Java 11 support. Job setting updated.
