### ISSUE TITLE
smallrye-converter-* artifactIds should IMHO be smallrye-reactive-converter-*

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-reactive-streams-operators#49]
Otherwise it suggests there's something more general to it.

**Comment by cescoffier** [comment]
The groupID indicate `reactive`, but I don't mind updating.

**Comment by cescoffier** [comment]
I've dropped "reactive" because it has already very long artifactIds such as:
`<artifactId>smallrye-converter-microprofile-reactive-streams-operators</artifactId>`

**Comment by Ladicek** [comment]
IMHO, the artifactId already strives to be unique, as it includes `smallrye`, which is also implied by the groupId. The MP RS Operators case is really ugly, but the other ones seems better.

Current | Suggested
------- | ---------
`smallrye-converter-api` | `smallrye-reactive-converter-api`
`smallrye-converter-microprofile-reactive-streams-operators` | `smallrye-reactive-converter-microprofile` or `smallrye-reactive-converter-mp-rs-operators`
`smallrye-converter-reactor` | `smallrye-reactive-converter-reactor`
`smallrye-converter-rxjava1` | `smallrye-reactive-converter-rxjava1`
`smallrye-converter-rxjava2` | `smallrye-reactive-converter-rxjava2`

I don't really mind, but I noticed the PR that adds documentation and the artifactIds struck me as somewhat confusing. I find the term "reactive converter" similar to "reactive stream operator".

**Comment by cescoffier** [comment]
in progress...

**Comment by cescoffier** [comment]
Done :-)
