### ISSUE TITLE
Wrong Error Management Operators doc section

### ISSUE THREAD

**Issue by ppatierno** [smallrye/smallrye-reactive-streams-operators#64]
The doc section related to the Error Management Operators is just a repetion of the previous Action  Operators section.
It doesn't describe the mentioned  onErroResume, onErrorResumeWith, onErrorResumeWithRsPublisher. Even the pictures are wrong.

**Comment by cescoffier** [comment]
Damned! Someone is reading the doc ;-)

Fixing it :-D
