### ISSUE TITLE
Compatibility with Android (aka JDK7)

### ISSUE THREAD

**Issue by kamalmarhubi** [smallrye/smallrye-reactive-streams-operators#79]
I was hoping to pair this library with a custom Reactive Streams implementation targeting Android. However, Android effectively only has JDK7 libraries available. (You can get JDK8 libraries by dropping support for about 35% of devices out there... not super palatable!)

In the section on the Reactive Streams dependency, the spec specifically calls out a desire to remain compatible with JDKs older than 9. Because of use of `CompletionStage`, `Function` and a few others, this actually means only JDK8. Is there any possibility of a version of this library that omits the those dependencies, or uses a vendorerd/shaded equivalent?

**Comment by cescoffier** [comment]
For Android, you should use RX Java 2 directly. 
This project is JDK 8+.
